# This is the tool that turns the package into a "wheel" which users can pip install
[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "hello-world"
dynamic = [
        "version"
]
authors = [
  { name="Jack Elvin-Poole" },
]
description = "An example of running Python code with Kubernetes."
readme = "README.md"
license = {file = "LICENSE"}
keywords = [
        "kubernetes",
        "python",
]
classifiers=[ 
        "Development Status :: 1 - Planning",
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3"
]
requires-python = ">=3.11" 
dependencies=[
    "numpy>=2.3.5",
]

[project.urls]
Homepage = "https://github.com/elvinpoole/k8s_example"
Repository = "https://github.com/elvinpoole/k8s_example"
Issues = "https://github.com/elvinpoole/k8s_example/issues"

[project.optional-dependencies]
dev = [
    "ruff",
    "pytest>=8.0,<9",
    "ipywidgets",
    "matplotlib",
    "mypy"
]

[project.scripts]
hello-world = "hello_world.cli:main"


[tool.hatch.version]
source = "vcs"

# This will automatically apply a version to the package when you make a new
# release. See the README "Releases" section for more.
[tool.hatch.build.hooks.vcs]
version-file = "src/hello_world/_version.py"

[tool.hatch.version.raw-options]
local_scheme = "no-local-version"

[tool.ruff]
# Apply to both src and tests by default
src = ["src", "tests"]
# maximum allowed line length
line-length = 100
# this ignores ambiguous variable names. Enable this if your project
# has a lot of equations with single character variables.
#ignore = ["E741"]

[tool.ruff.format]
# use double quotes for strings.
quote-style = "double"
# indent with spaces, rather than tabs.
indent-style = "space"
# respect magic trailing commas.
skip-magic-trailing-comma = false

[tool.ruff.lint]
# Can expand this as far as user wants
select = [
 "E",   # pycodestyle (PEP8) errors
 "F",   # pyflakes
 "I",   # isort-like import sorting
 "B",   # bugbear (common bugs)
 "UP",  # pyupgrade (modern Python idioms)
]
[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.mypy]
packages = ["hello_world"]
ignore_missing_imports = true
strict = true