{{/*
This is the Helm equivalent of the k8s/job.yaml file.
Expressions inside double braces insert values or run template logic and helpers.
*/}}

{{- if .Values.job.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.job.name }}
  labels:
    {{- include "hello-world.labels" . | nindent 4 }}
spec:
  backoffLimit: {{ .Values.job.backoffLimit }}
  template:
    spec:
      restartPolicy: {{ .Values.job.restartPolicy }}
      containers:
        - name: {{ .Values.job.name }}
          image: {{ include "hello-world.image" (dict "image" .Values.job.image "global" .Values.global) }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
{{- end }}
